# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{serial-scheduler}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andi Bade"]
  s.date = %q{2011-02-28}
  s.description = %q{Schedule Task – execute all tasks at the same time one after another}
  s.email = %q{andi@galaxycats.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/serial-scheduler.rb",
     "lib/serial_scheduler.rb",
     "lib/serial_scheduler/converter.rb",
     "lib/serial_scheduler/date_day_names_core_extension.rb",
     "lib/serial_scheduler/dsl.rb",
     "lib/serial_scheduler/runner.rb",
     "lib/serial_scheduler/time_table.rb",
     "serial-scheduler.gemspec",
     "test/converter_test.rb",
     "test/dsl_test.rb",
     "test/runner_test.rb",
     "test/serial_scheduler_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/thyphoon/serial-scheduler}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Schedule Task – execute all tasks at the same time one after another}
  s.test_files = [
    "test/converter_test.rb",
     "test/dsl_test.rb",
     "test/runner_test.rb",
     "test/serial_scheduler_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

